//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Telemetry.OnlineWebReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://telemetry.azurewebsites.net/RaceUpload", ConfigurationName="OnlineWebReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://telemetry.azurewebsites.net/RaceUpload is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://telemetry.azurewebsites.net/RaceUpload/UploadRace", ReplyAction="*")]
        F1Telemetry.OnlineWebReference.UploadRaceResponse UploadRace(F1Telemetry.OnlineWebReference.UploadRaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://telemetry.azurewebsites.net/RaceUpload/UploadRace", ReplyAction="*")]
        System.Threading.Tasks.Task<F1Telemetry.OnlineWebReference.UploadRaceResponse> UploadRaceAsync(F1Telemetry.OnlineWebReference.UploadRaceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadRaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadRace", Namespace="http://telemetry.azurewebsites.net/RaceUpload", Order=0)]
        public F1Telemetry.OnlineWebReference.UploadRaceRequestBody Body;
        
        public UploadRaceRequest() {
        }
        
        public UploadRaceRequest(F1Telemetry.OnlineWebReference.UploadRaceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://telemetry.azurewebsites.net/RaceUpload")]
    public partial class UploadRaceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int track;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fastestLap;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double sector1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double sector2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double sector3;
        
        public UploadRaceRequestBody() {
        }
        
        public UploadRaceRequestBody(string username, string password, int track, string fastestLap, double sector1, double sector2, double sector3) {
            this.username = username;
            this.password = password;
            this.track = track;
            this.fastestLap = fastestLap;
            this.sector1 = sector1;
            this.sector2 = sector2;
            this.sector3 = sector3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadRaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadRaceResponse", Namespace="http://telemetry.azurewebsites.net/RaceUpload", Order=0)]
        public F1Telemetry.OnlineWebReference.UploadRaceResponseBody Body;
        
        public UploadRaceResponse() {
        }
        
        public UploadRaceResponse(F1Telemetry.OnlineWebReference.UploadRaceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://telemetry.azurewebsites.net/RaceUpload")]
    public partial class UploadRaceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadRaceResult;
        
        public UploadRaceResponseBody() {
        }
        
        public UploadRaceResponseBody(string UploadRaceResult) {
            this.UploadRaceResult = UploadRaceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : F1Telemetry.OnlineWebReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<F1Telemetry.OnlineWebReference.WebServiceSoap>, F1Telemetry.OnlineWebReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        F1Telemetry.OnlineWebReference.UploadRaceResponse F1Telemetry.OnlineWebReference.WebServiceSoap.UploadRace(F1Telemetry.OnlineWebReference.UploadRaceRequest request) {
            return base.Channel.UploadRace(request);
        }
        
        public string UploadRace(string username, string password, int track, string fastestLap, double sector1, double sector2, double sector3) {
            F1Telemetry.OnlineWebReference.UploadRaceRequest inValue = new F1Telemetry.OnlineWebReference.UploadRaceRequest();
            inValue.Body = new F1Telemetry.OnlineWebReference.UploadRaceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.track = track;
            inValue.Body.fastestLap = fastestLap;
            inValue.Body.sector1 = sector1;
            inValue.Body.sector2 = sector2;
            inValue.Body.sector3 = sector3;
            F1Telemetry.OnlineWebReference.UploadRaceResponse retVal = ((F1Telemetry.OnlineWebReference.WebServiceSoap)(this)).UploadRace(inValue);
            return retVal.Body.UploadRaceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<F1Telemetry.OnlineWebReference.UploadRaceResponse> F1Telemetry.OnlineWebReference.WebServiceSoap.UploadRaceAsync(F1Telemetry.OnlineWebReference.UploadRaceRequest request) {
            return base.Channel.UploadRaceAsync(request);
        }
        
        public System.Threading.Tasks.Task<F1Telemetry.OnlineWebReference.UploadRaceResponse> UploadRaceAsync(string username, string password, int track, string fastestLap, double sector1, double sector2, double sector3) {
            F1Telemetry.OnlineWebReference.UploadRaceRequest inValue = new F1Telemetry.OnlineWebReference.UploadRaceRequest();
            inValue.Body = new F1Telemetry.OnlineWebReference.UploadRaceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.track = track;
            inValue.Body.fastestLap = fastestLap;
            inValue.Body.sector1 = sector1;
            inValue.Body.sector2 = sector2;
            inValue.Body.sector3 = sector3;
            return ((F1Telemetry.OnlineWebReference.WebServiceSoap)(this)).UploadRaceAsync(inValue);
        }
    }
}
